workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,21 +18,30 @@ jobs:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         HOST: ${{ secrets.DIGITALOCEAN_HOST }}
       run: |
+        if [ -z "$SSH_PRIVATE_KEY" ]; then
+          echo "Error: SSH_PRIVATE_KEY is not set." >&2
+          exit 1
+        fi
         if [ -z "$HOST" ]; then
           echo "Error: DIGITALOCEAN_HOST is not set." >&2
           exit 1
         fi
-        mkdir -p ~/.ssh
-        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
-        chmod 600 ~/.ssh/id_rsa
-        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
 
-    - name: Check environment variables
+        mkdir -p ~/.ssh
+        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
+        chmod 600 ~/.ssh/id_rsa
+
+        # Verify known hosts setup
+        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
+        cat ~/.ssh/known_hosts
+
+    - name: Verify SSH connection
+      env:
+        USER: ${{ secrets.DIGITALOCEAN_USER }}
+        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
+        PORT: ${{ secrets.DIGITALOCEAN_PORT }}
       run: |
-        echo "HOST: ${{ secrets.DIGITALOCEAN_HOST }}"
-        echo "USER: ${{ secrets.DIGITALOCEAN_USER }}"
-        echo "PORT: ${{ secrets.DIGITALOCEAN_PORT }}"
-        echo "REMOTE_DIR: ${{ secrets.DIGITALOCEAN_REMOTE_DIR_SD }}"
+        ssh -o StrictHostKeyChecking=no -p $PORT $USER@$HOST "echo 'SSH connection successful!'"
 
     - name: Deploy files to DigitalOcean
       env:
