workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,11 +16,23 @@ jobs:
     - name: Set up SSH
       env:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+        HOST: ${{ secrets.DIGITALOCEAN_HOST }}
       run: |
+        if [ -z "$HOST" ]; then
+          echo "Error: DIGITALOCEAN_HOST is not set." >&2
+          exit 1
+        fi
         mkdir -p ~/.ssh
         echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
-        ssh-keyscan -H ${{ secrets.DIGITALOCEAN_HOST }} >> ~/.ssh/known_hosts
+        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
+
+    - name: Check environment variables
+      run: |
+        echo "HOST: ${{ secrets.DIGITALOCEAN_HOST }}"
+        echo "USER: ${{ secrets.DIGITALOCEAN_USER }}"
+        echo "PORT: ${{ secrets.DIGITALOCEAN_PORT }}"
+        echo "REMOTE_DIR: ${{ secrets.DIGITALOCEAN_REMOTE_DIR_SD }}"
 
     - name: Deploy files to DigitalOcean
       env:
